plugins {
    id 'java'
}

group = 'main'
version = '0.1-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url = uri('https://jitpack.io') }
    maven { url = uri('https://raw.githubusercontent.com/Zelaux/MindustryRepo/master/repository') }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    compileOnly "com.github.Anuken.Mindustry:core:v159.7"
    compileOnly "com.github.Anuken.Arc:arc-core:v159.7"

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}